[env]
# Gate OS config
GATEOS_MEMORY = 32
SERIAL_ENABLED = true
MONITOR_ENABLED = false
DEBUG_SYMBOLS_ENABLED = false
LLDB_ENABLED = false
UEFI_ENABLED = true
# Bootloader config
BOOTLOADER_SERIAL_LOGGING = false

[env.lldb]
MONITOR_ENABLED = false
DEBUG_SYMBOLS_ENABLED = true
LLDB_ENABLED = true

[tasks.format]
command = "cargo"
args = ["fmt"]
workspace = false

[tasks.build-user-rust]
script = [
    "basename -s .rs kernel/src/bin/*.rs | xargs -I {} touch kernel/dsk/bin/{}",
    # Add env to enable -g
    "(cd kernel && basename -s .rs kernel/src/bin/*.rs | xargs -I {} cargo rustc --no-default-features --features userspace --release --bin {})",
    "basename -s .rs kernel/src/bin/*.rs | xargs -I {} cp target/x86_64-unknown-none/release/{} kernel/dsk/bin/{}",
    "strip kernel/dsk/bin/*"
]
dependencies = ["format"]
workspace = false

[tasks.build]
condition = { env_true = ["DEBUG_SYMBOLS_ENABLED"], env = { "RUSTFLAGS" = '-g' } }
command = "cargo"
args = ["build"]
dependencies = ["build-user-rust"]
workspace = false

[tasks.qemu]
command = "cargo"
args = ["run"]
dependencies = ["build"]
workspace = false