[tasks.set-vars]
script_runner = "@duckscript"
script = '''
set_env MAKEFLAGS "${MAKEFLAGS} -rR"

if is_empty ${RUST_PROFILE}
    RUST_PROFILE = set "dev"
    set_env RUST_PROFILE ${RUST_PROFILE}
end

if eq "${RUST_PROFILE} " "dev "
    set_env RUST_PROFILE_SUBDIR "debug"
else
    set_env RUST_PROFILE_SUBDIR ${RUST_PROFILE}
end
'''

[tasks.all]
dependencies = [ "set-vars", "build" ]
script = "cp target/x86_64-unknown-none/${RUST_PROFILE_SUBDIR}/limine-rust-template kernel"

[tasks.build]
dependencies = [ "set-vars" ]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-none", "--profile", "${RUST_PROFILE}"]

[tasks.clean]
dependencies = [ "clean-rust" ]
script = "rm -rf kernel"

[tasks.clean-rust]
command = "cargo"
args = ["clean"]

[tasks.distclean]
dependencies = [ "clean" ]