[package]
name = "hal-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics-core = { version = "0.4", optional = true }
log = "0.4.20"
spin = "0.9.8"